import type { ProjectionOverlaySettings } from './types';

/** Settings the app starts with; captures start from the same look. */
export const createDefaultProjectionSettings = (): ProjectionOverlaySettings => ({
    enabled: true,
    styleMode: 'animationStable',
    simplifyEpsilon: 0,
    strokeWidth: 1.25,
    showContours: false,
    opacity: 1,
    minTriangleCount: 1,
    backgroundColor: '#FFA8A8',
    outlineColor: '#51443D',
    outlineOpacity: 0.72,
    shadowStrength: 0.38,
    highlightStrength: 0.24,
    shadowThreshold: -0.30,
    highlightThreshold: 0.62,
    lightDirection: [0.35, 0.8, 0.45],
    minShapeArea: 0,
    fillBleed: 0,
    respectMaterialVisibility: true,
    depthVisibilityTolerance: 1e-7,
    useAuthoredNormals: true,
    preserveRasterContours: true,
    flickerControl: {
        shadeHysteresis: 0.02,
        regionHysteresis: 0,
        normalSmoothing: 0,
        reuseOutputCapacity: true,
        stableOpaqueFill: true,
    },
    edgeRoughness: 0.35,
    edgeSmoothing: 'soft',
    enableComposition: false,
    enableShapeTracking: false,
    enableEdgeDistortion: false,
    compositionMode: 'vector',
    boundaryGuard: 'outerDepthNormal',
    depthMergeThreshold: 0.035,
    normalMergeThreshold: 0.61,
    gapMergeThreshold: 1.5,
    temporalStability: 0.78,
    globalShapeBudget: 96,
    focusShapeBudgets: {
        focal: 40,
        support: 28,
        abstract: 12,
    },
    mergeColorThreshold: 0.12,
    partOverrides: {},
    cpuRasterBackend: 'auto',
});
